import React from "react";
import "./globals.css"; // Importing global CSS styles
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar"; // Importing the Navbar component
import Footer from "./components/Footer"; // Importing the Footer component

// Initializing the Inter font with the 'latin' subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for your Next.js application
export const metadata: Metadata = {
  title: "Create Resume App",
  description: "Generated by create next app",
};

// RootLayout component definition
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {/* Render the child components passed to this layout */}
        {children}
        {/* Render the Footer component */}
        <Footer />
      </body>
    </html>
  );
}

// Explanation
// useEffect is used to run code after the component is mounted. It initializes the AOS library only in a browser environment.
//The inter constant initializes the Inter font with the "latin" subset.
//metadata contains metadata for your Next.js application, including the title and description.
//The RootLayout component is a higher-order component that wraps the main content of your pages. It includes the Navbar, the content passed as children, and the Footer.
//The Navbar and Footer components are imported and rendered within the layout.
// This layout component ensures that your application has consistent styling, font loading, and animations using the AOS library. You can use it as a wrapper around your 
//individual page components to maintain a consistent layout structure.